---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: dev
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
