---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "new deploy for robo website"
spec:
  selector:
    matchLabels:
      app: my-app
  template: 
    metadata:
      labels:
        app: my-app
    spec:
      containers: 
      - name: my-container
        image: anildoc143/nginx:mario
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "150Mi"
          limits:
            cpu: "300m"
            memory: "300Mi"
        livenessProbe:  # Added liveness probe for better monitoring
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:  # Added readiness probe to handle traffic only when ready
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
